[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_blinks_actions = "39U7QAQMoAKJbDAgu271jhSrbYBnN8fp6e2qDs4erE8z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
